### ISSUE TITLE
Make package build against distributed-process-0.7.4

### ISSUE THREAD

**Issue by philipcunningham** [haskell-distributed/distributed-process-registry#1]
I've been experimenting with `distributed-process` and found myself reaching for a process registry. Unfortunately this package doesn't build with `distributed-process-0.7.4`.

**Comment by hyperthunk** [comment]
Hmmm. What are the compilation errors? I haven't even got a dev environment set up at the moment, but I can start pulling one together and see if I can fix.
